// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBD88BMO3A9V6SoxCIhzsxkwgd7wlPU66A',
    appId: '1:503152360191:web:4f2aa8465764f1e6246aca',
    messagingSenderId: '503152360191',
    projectId: 'mathbooking-96998',
    authDomain: 'mathbooking-96998.firebaseapp.com',
    storageBucket: 'mathbooking-96998.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHswHJwcdFWlbqjuhjXucKFHIowv5ez0c',
    appId: '1:503152360191:android:a28eba657080a1da246aca',
    messagingSenderId: '503152360191',
    projectId: 'mathbooking-96998',
    storageBucket: 'mathbooking-96998.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZVuao2X6uyFA8dxF3WtRepspnCbTZQ4o',
    appId: '1:503152360191:ios:d6b7ba6a2a209ff6246aca',
    messagingSenderId: '503152360191',
    projectId: 'mathbooking-96998',
    storageBucket: 'mathbooking-96998.firebasestorage.app',
    iosBundleId: 'com.example.flutterAppl',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZVuao2X6uyFA8dxF3WtRepspnCbTZQ4o',
    appId: '1:503152360191:ios:d6b7ba6a2a209ff6246aca',
    messagingSenderId: '503152360191',
    projectId: 'mathbooking-96998',
    storageBucket: 'mathbooking-96998.firebasestorage.app',
    iosBundleId: 'com.example.flutterAppl',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBD88BMO3A9V6SoxCIhzsxkwgd7wlPU66A',
    appId: '1:503152360191:web:ce79c36fab1892a8246aca',
    messagingSenderId: '503152360191',
    projectId: 'mathbooking-96998',
    authDomain: 'mathbooking-96998.firebaseapp.com',
    storageBucket: 'mathbooking-96998.firebasestorage.app',
  );
}
